### ISSUE TITLE
Task Specification Format

### ISSUE THREAD

**Issue by tbgiles** [projectpolygon/hypercube#3]
Each render should be started by submitting a "Task Specification File" to the system, which will specify all inputs and outputs of the system task. This may be broken into smaller sub-tasks, but the result of this issue should be a file format that will be simple to parse via Go and C++, and must be able to be changed easily.

Some information to get started:
- Must be able to specify a series of input .obj files. Each of these may require several materials, and so each input .obj must have a list of possible materials attached.
- Must be able to specify a chunking size
- Must be able to specify level of detail (resolution, samples per pixel (AA), ambient occlusion samples, ambient occlusion hemisphere tightness.
- Must be able to specify the default colour of each object.
- Must be able to specify the texture file mapped to each object
- It may be useful to use a JSON parser to simplify the rules of the format. See [this](https://github.com/DaveGamble/cJSON)
- Must be readable/writable in C++

Please discuss within this issue.

**Comment by tbgiles** [comment]
using other issue to track

**Comment by JonParkes** [comment]
covered in othe smaller tasks
